# This rule is not used by the project gno-node-health itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to monitoring.k8s.gno.land resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gno-node-health
    app.kubernetes.io/managed-by: kustomize
  name: gnonodehealth-viewer-role
rules:
- apiGroups:
  - monitoring.k8s.gno.land
  resources:
  - gnonodehealths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.k8s.gno.land
  resources:
  - gnonodehealths/status
  verbs:
  - get
